version: '3.8'

services:
  ais-proxy:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AISSTREAM_API_KEY=${AISSTREAM_API_KEY}
      - DEFAULT_BOUNDING_BOX=[[-48.0,166.0],[-34.0,179.0]]
      - PORT=3000
    restart: unless-stopped